services:
  db:
    image: mariadb:noble
    environment:
      - TZ=America/Sao_Paulo
      - MARIADB_ROOT_PASSWORD=qwe123
    ports:
      - 3306:3306
    volumes:
      - ./database/marmelada.sql:/docker-entrypoint-initdb.d/marmelada.sql
      - mariadbdata:/var/lib/mysql
    networks:
      - marmelada-network
  php-fpm:
    image: php:8.1.32-fpm-alpine
    environment:
      - TZ=America/Sao_Paulo
    command: sh -c "docker-php-ext-install pdo_mysql && docker-php-entrypoint php-fpm"
    volumes:
      - ../app/:/var/www/cafeteria-marmelada/app/
    networks:
      - marmelada-network
  nginx:
    image: nginx:stable-alpine
    depends_on:
      php-fpm:
        condition: service_healthy
    ports:
      - 80:80
    networks:
      - marmelada-network
    volumes:
      - ./web/marmelada.conf:/etc/nginx/conf.d/default.conf
      - ../app/:/var/www/cafeteria-marmelada/app/
      - ../logs/:/var/www/cafeteria-marmelada/logs/

networks:
  marmelada-network:
    driver: bridge

volumes:
  mariadbdata:
    driver: local