services:
  db:
    build: ./database
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - marmelada-network
  php-fpm:
    build: ./web/php
    volumes:
      - ../app/:/var/www/cafeteria-marmelada/app/
    networks:
      - marmelada-network
    restart: unless-stopped
  nginx:
    build: ./web/nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
    networks:
      - marmelada-network
    volumes:
      - ../app/:/var/www/cafeteria-marmelada/app/
      - ../logs/:/var/www/cafeteria-marmelada/logs/

networks:
  marmelada-network:
    driver: bridge

volumes:
  mariadbdata:
    driver: local